#NEI <- readRDS("summarySCC_PM25.rds")
#SCC <- readRDS("Source_Classification_Code.rds")
vehicleSCCs <- unique(SCC[c(grep("Motor|Vehicle", SCC$SCC.Level.Three), grep("Motor|Vehicle", SCC$EI.Sector)), "SCC"])
vehicleNEI <- subset(NEI, SCC %in% vehicleSCCs)
vehicleBaltimoreNEI <- subset(vehicleNEI, fips == "24510")
vehicleLaNEI <- subset(vehicleNEI, fips == "06037")
baltimoreByYear <- aggregate(vehicleBaltimoreNEI$Emissions, by=list(year=vehicleBaltimoreNEI$year), FUN=sum)
LaByYear <- aggregate(vehicleLaNEI$Emissions, by=list(year=vehicleLaNEI$year), FUN=sum)
png(filename = "plot6.png", width = 480, height = 480)
layout(matrix(c(1,2,3,3), ncol=2, byrow=TRUE), heights=c(4, 1))
par(mai=rep(0.5, 4))
barplot(baltimoreByYear$x/1000, names.arg=baltimoreByYear$year, ylab="PM2.5 emissions (1000 tons)", col="blue")
barplot(LaByYear$x/1000, names.arg=LaByYear$year, ylab="PM2.5 emissions (1000 tons)", col="red")
par(mai=c(0,0,0,0))
plot.new()
legend('topright', pch=1, col=c('blue', 'red'), legend=c("Baltimore", "Los Angeles"))
dev.off()